EasyEstimation.Web/Models/ErrorViewModel.cs
using System;

namespace EasyEstimation.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EasyEstimation.Web/Models/ImageUploadModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasyEstimation.Web.Models
{
    public class ImageUploadModel
    {
        public int Id { get; set; }

        public IFormFile FormFile { get; set; }
    }
}

EasyEstimation.Web/Models/SubFeatureModel.cs
using System.Collections.Generic;

namespace EasyEstimation.Web.Models
{
    public class SubFeatureModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        
        public int ImageId { get; set; }
        
        public string Description { get; set; }
    }
}

EasyEstimation.Web/Models/UserModel.cs
namespace EasyEstimation.Web.Models
{
    public class UserModel
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public bool IsAdmin { get; set; }
    }
}

EasyEstimation.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace EasyEstimation.Web.Controllers
{
    public class BaseController : Controller
    {
     
    }
}

EasyEstimation.Web/Controllers/HomeController.cs
using EasyEstimation.Web.Models;
using EasyEstimation.Web.Resources;
using EasyEstimation.Web.Resources.Abstracts;
using EasyEstimation.Web.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EasyEstimation.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMessageManager _messageManager;
        private readonly IAdminService _adminService;

        public HomeController(ILogger<HomeController> logger, IMessageManager messageManager, IAdminService adminService)
        {
            _logger = logger;
            _messageManager = messageManager;
            _adminService = adminService;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Index function gets all users");
            _messageManager.GetMessage(MessageKeys.US_MSG_01);

            var allUsers = _adminService.GetUsers().Result;

            return View(allUsers);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EasyEstimation.Web/Controllers/SubFeatureController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using EasyEstimation.Web.Models;
using EasyEstimation.Web.Resources;
using EasyEstimation.Web.Resources.Abstracts;
using EasyEstimation.Web.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;
using EasyEstimation.Utilities;

namespace EasyEstimation.Web.Controllers
{
    public class SubFeatureController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMessageManager _messageManager;
        private readonly ISubFeatureService _SubFeatureService;
        private readonly INotyfService _notyf;

        public SubFeatureController(ILogger<HomeController> logger, IMessageManager messageManager, ISubFeatureService SubFeatureService, INotyfService notyf)
        {
            _logger = logger;
            _messageManager = messageManager;
            _SubFeatureService = SubFeatureService;
            _notyf = notyf;
        }

        public IActionResult Index()
        {
            _messageManager.GetMessage(MessageKeys.SF_MSG_01);
           
            var allSubFeatures = _SubFeatureService.GetSubFeatures().Result;
            
            return View("SubFeatureView", allSubFeatures);
        }

        public IActionResult AddSubFeature(SubFeatureModel model) {
            _logger.LogInformation("SubFeature is being added");
            _SubFeatureService.AddSubFeature(model);
            var allSubFeatures = _SubFeatureService.GetSubFeatures().Result;
            _notyf.Success("Record Added Successfully");
            return View("SubFeatureView", allSubFeatures);
        }
        [HttpGet("[action]")]
        public IActionResult AddRedirect()
        {
            return View("SubFeatureActionView");
        }
        public IActionResult UploadRedirect()
        {
            return View("SubFeatureFileUploadView");
        }

        [HttpGet("[action]")]
        public IActionResult EditRedirect() {            
               return View("SubFeatureEditView");
        }

        public IActionResult EditSubFeature(SubFeatureModel model) {

            _SubFeatureService.ModifySubFeature(model);
            var allSubFeatures = _SubFeatureService.GetSubFeatures().Result;
            _notyf.Success("Record Edited Successfully");
            return View("SubFeatureView", allSubFeatures);
        }
        public IActionResult DeleteSubFeature(int id) {
            _SubFeatureService.DeleteSubFeatureById(id);
            var allSubFeatures = _SubFeatureService.GetSubFeatures().Result;
            _notyf.Success("Record Deleted Successfully");
            return View("SubFeatureView", allSubFeatures);
        }
        public async Task<IActionResult> FileUpload(ImageUploadModel model) {
            var File = model.FormFile;
            string path = await ImageSaver.Saver(File, "SubFeatureImages");
            return View("SubFeatureFileUploadView");
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EasyEstimation.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EasyEstimation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EasyEstimation.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EasyEstimation.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EasyEstimation.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EasyEstimation.Web/Views/SubFeature/SubFeatureActionView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model EasyEstimation.Web.Models.SubFeatureModel
<center>
    <h1>AddSubFeature</h1>
    <form asp-action="AddSubFeature" asp-controller="SubFeature" type="post">
        <table class="table-active">
            <tr>
                <td>
                    SubFeatureName
                </td>
                <td>
                    <input id="SubFeatureName" type="text" asp-for="Name" class="form-control">
                </td>
            </tr>
            <tr>
                <td>
                    SubFeatureImageId
                </td>
                <td>
                    <input id="SubFeatureImageId" type="text" asp-for="ImageId" class="form-control">
                </td>
            </tr>
            <tr>
                <td>
                    SubFeatureDescription
                </td>
                <td>
                    <input id="SubFeatureDescription" type="text" asp-for="Description" class="form-control">
                </td>
            </tr>
        </table>
        <br>
        <br>
        <input type="submit" class="btn-primary" id="Add" value="ADD" asp-action="AddSubFeature">
    </form>
</center>

EasyEstimation.Web/Views/SubFeature/SubFeatureEditView.cshtml
@model EasyEstimation.Web.Models.SubFeatureModel

@{
    ViewData["Title"] = "SubFeatureEditView";
}

<h1>SubFeatureEditView</h1>

<h4>SubFeatureModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditSubFeature">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageId" class="control-label"></label>
                <input asp-for="ImageId" class="form-control" />
                <span asp-validation-for="ImageId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" asp-action="EditSubFeature"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="SubFeatureView">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EasyEstimation.Web/Views/SubFeature/SubFeatureFileUploadView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model EasyEstimation.Web.Models.ImageUploadModel
<center>
    <h3> File Upload View</h3>
    <br>
<form enctype="multipart/form-data" method="post" asp-controller="SubFeature" asp-action="FileUpload">
    <Table>
        <tr>
            <td>
                <label asp-for="Id"></label>
            </td>
            <td>
                <input asp-for="Id" type="text">
            </td>
            </tr>
        <tr>
            <td>
                <label class="form-control"></label>
            </td>
            <td>
                <input class="form-control" asp-for="FormFile" type="file">
            </td>
        </tr>
    </Table>
    <input asp-controller="SubFeature" asp-action="FileUpload" class="btn" type="submit" value="Upload" />
</form>
</center>

EasyEstimation.Web/Views/SubFeature/SubFeatureView.cshtml
@model IEnumerable<EasyEstimation.Web.Models.SubFeatureModel>

@{
    ViewData["Title"] = "View";
}

<h1>SubFeatureView</h1>

<a class="btn-primary" value="EDIT" asp-action="AddRedirect" asp-controller="SubFeature">
    <input type="button" value="ADD" class="btn-primary">
</a>
<a class="btn-primary" value="EDIT" asp-action="UploadRedirect" asp-controller="SubFeature">
    <input type="button" value="UPLOAD" class="btn-primary">
</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ImageId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a class="btn-primary" value="EDIT" asp-action="EditRedirect" asp-controller="SubFeature" asp-route-id="@item.Id">
                        <input type="button" value="EDIT" class="btn-primary">
                    </a>
                    <a class="btn-primary" value="DELETE" asp-action="DeleteSubFeature" asp-controller="SubFeature" asp-route-id="@item.Id">
                        <input type="button" value="DELETE" class="btn-primary">
                    </a>
                </td>

            </tr>
        }
    </tbody>
</table>
@section Scripts{
    <script>
        $("document").ready($("#Edit").click(
            function () {

            }
        ))
    </script>
} 